"""initial schema

Revision ID: 5ee3b5f4876c
Revises: 
Create Date: 2026-07-08 19:16:33.099890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ee3b5f4876c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('counters',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('divisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('l1_approver_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['l1_approver_id'], ['users.id'], name='fk_division_l1_approver', ondelete='NO ACTION', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('roles', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('division_id', sa.String(length=36), nullable=True),
    sa.Column('delegate_id', sa.String(length=36), nullable=True),
    sa.Column('failed_logins', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token_expiry', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['delegate_id'], ['users.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('reset_token'),
    sa.UniqueConstraint('username')
    )
    op.create_table('approval_thresholds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('approver_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level')
    )
    op.create_table('capex_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('requestor_id', sa.String(length=36), nullable=False),
    sa.Column('assignee_id', sa.String(length=36), nullable=True),
    sa.Column('division_id', sa.String(length=36), nullable=True),
    sa.Column('request_date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('budgeted', sa.Boolean(), nullable=False),
    sa.Column('replacement', sa.Boolean(), nullable=False),
    sa.Column('health_safety', sa.Boolean(), nullable=False),
    sa.Column('revenue_generating', sa.Boolean(), nullable=False),
    sa.Column('environmental', sa.Boolean(), nullable=False),
    sa.Column('competitive_bids', sa.Boolean(), nullable=False),
    sa.Column('lease_recommended', sa.Boolean(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('effect_on_operations', sa.Text(), nullable=False),
    sa.Column('asset_life', sa.String(length=100), nullable=True),
    sa.Column('irr_after_tax', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('first_year_ebit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('annual_savings', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('payback_years', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('npv_savings', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cost_autos_trucks', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cost_machinery', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cost_improvements', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cost_furniture', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cost_permits', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cost_misc', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('finance_completed', sa.Boolean(), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('required_levels', sa.Integer(), nullable=False),
    sa.Column('current_level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['requestor_id'], ['users.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('approval_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('acted_for_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['acted_for_id'], ['users.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['request_id'], ['capex_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=150), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['capex_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=10), nullable=False),
    sa.Column('type', sa.String(length=150), nullable=False),
    sa.Column('make', sa.String(length=150), nullable=False),
    sa.Column('model', sa.String(length=150), nullable=False),
    sa.Column('cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['capex_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['capex_requests.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_logs')
    op.drop_table('equipment_items')
    op.drop_table('attachments')
    op.drop_table('approval_actions')
    op.drop_table('capex_requests')
    op.drop_table('approval_thresholds')
    op.drop_table('users')
    op.drop_table('divisions')
    op.drop_table('counters')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
